# Generated by Django 5.0.14 on 2026-10-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('tipo_mascota', models.CharField(max_length=50)),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
